from utils.widgets import*

def historytxt():
    writeonscreen("Their are many games related to space fighting few are mentioned above", width/2, 370, 10)
    writeonscreen("Space Invaders: is a 1978 arcade game created by Tomohiro Nishikado.", width/2, 370 + 12, 10)
    writeonscreen("Space Invaders was the first fixed space shooting game and it set the template for the shoot 'em up genre", width/2, 370 + 2*12, 10)
    writeonscreen("Space Invaders was an immediate commercial success; by 1982, it had grossed $3.8 billion, with a net profit of $450 million", width/2, 370 + 3*12, 10)
    writeonscreen("making it the best-selling video game and highest-grossing 'entertainment product' at the time", width/2, 370 + 4*12, 10)
    writeonscreen("Earlier shooting games allowed players to shoot targets,Space Invaders was the first in which targets could fire back at player.", width/2, 370 + 5*12, 10)
    writeonscreen("It was also the first game where players were given multiple lives, had to repel hordes of enemies,", width/2, 370 + 6*12, 10)
    writeonscreen("could take cover from enemy fire, and use destructible barriers,", width/2, 370 + 7*12, 10)
    writeonscreen("Miyamoto considers Space Invaders to be the game that revolutionized the video game industry", width/2, 370 + 8*12, 10)
    writeonscreen("Deus creator of Warren Spector said: Space Invaders & games like it represent roots of everything we see today in gaming", width/2, 370 + 9*12, 10)
    writeonscreen("Edge magazine attributed shift of games from bars & arcades to more mainstream locations, such as restaurants and stores", width/2, 370 + 10*12, 10)
    writeonscreen("And this is all due to this game space Invasion", width/2, 370 + 11*12, 10)
    writeonscreen("Its popularity was such that it was the first game where an arcade machine's owner could", width/2, 370 + 12*12, 10)
    writeonscreen("make up for the cost of the machine in under one month and less", width/2, 370 + 13*12, 10)
    writeonscreen("Guinness World Records considered Space Invaders one of the most successful arcade shooting games by 2008.", width/2, 370 + 14*12, 10)
    writeonscreen("Its worldwide success created demand for a wide variety of science fiction games,inspiring the dev. of arcade games,such as", width/2, 370 + 15*12, 10)
    writeonscreen("Atari's Asteroids,Williams' Defender, & Namco's Galaxian which were modeled after Space Invaders's gameplay & design", width/2, 370 + 16*12, 10)
